{
 "title": "risingwave_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "sst counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(storage_level_sst_num) by (instance, level_index)",
     "legendFormat": "{{level_index}}"
    }
   ]
  },
  {
   "title": "compaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "storage_level_compact_frequency",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "compact duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_compact_task_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-task p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_task_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-task p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le)(rate(state_store_compact_task_duration_sum[1m])) / sum by(le) (rate(state_store_compact_task_duration_count[1m]))",
     "legendFormat": "compact-task avg"
    },
    {
     "expr": "sum by(le)(rate(state_store_compact_sst_duration_sum[1m])) / sum by(le) (rate(state_store_compact_sst_duration_count[1m]))",
     "legendFormat": "compact-key-range avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_sst_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-key-range p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_table_id_total_time_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "get-table-id p90 {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_remote_read_time_per_task_bucket[1m])) by (le, job, instance))",
     "legendFormat": "remote-io p90 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "compact throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_compaction_read_bytes[1m]))by(job,instance)",
     "legendFormat": "read - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_compaction_write_bytes[1m]))by(job,instance)",
     "legendFormat": "write - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_write_build_l0_bytes[1m]))by (job,instance)",
     "legendFormat": "flush - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "compacting sst count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "storage_level_compact_cnt", "legendFormat": "{{level_index}}" }
   ]
  },
  {
   "title": "Hummock Version Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "version_size / 1024.0", "legendFormat": "version size" },
    {}
   ]
  },
  {
   "title": "GBs read from next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_read_next_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read bytes p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_read_next_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read bytes p99"
    }
   ]
  },
  {
   "title": "GBs read from current level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_read_curr_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read bytes p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_read_curr_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read bytes p99"
    }
   ]
  },
  {
   "title": "count of sst read from current level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_read_sstn_curr_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_read_sstn_curr_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} p99"
    }
   ]
  },
  {
   "title": "GBs written to next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_write_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} write bytes p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_write_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} write bytes p99"
    }
   ]
  },
  {
   "title": "count of sst written to next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_write_sstn_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} write count p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_write_sstn_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} write count p99"
    }
   ]
  },
  {
   "title": "count of sst read from next level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(storage_level_compact_read_sstn_next_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read count p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_level_compact_read_sstn_next_bucket[1m])) by (le, level_index))",
     "legendFormat": "{{level_index}} read count p99"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(object_store_read_bytes[1m]))by(job,instance)",
     "legendFormat": "read - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(object_store_write_bytes[1m]))by(job,instance)",
     "legendFormat": "write - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "operation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(object_store_operation_latency_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}} p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(object_store_operation_latency_bucket[1m])) by (le, type, job, instance))",
     "legendFormat": "{{type}} p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_latency_bucket[1m])) by (le, job, instance))",
     "legendFormat": "{{type}} p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, type)(rate(object_store_operation_latency_sum[1m])) / sum by(le, type) (rate(object_store_operation_latency_count[1m]))",
     "legendFormat": "{{type}} avg"
    }
   ]
  },
  {
   "title": "ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(object_store_operation_latency_count[1m])) by (le, type, job, instance)",
     "legendFormat": "{{type}} - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "ops size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_bytes_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}  p90"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(object_store_operation_bytes_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}} p80"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "barrier latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum[1m]) / rate(meta_barrier_duration_seconds_count[1m])",
     "legendFormat": "barrier_latency_avg"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p999"
    }
   ]
  },
  {
   "title": "actor throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stream_actor_row_count[15s])",
     "legendFormat": "actor_id = {{actor_id}}"
    }
   ]
  },
  {
   "title": "source throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "rows/s" }
   ],
   "targets": [
    {
     "expr": "rate(stream_source_output_rows_counts[15s])",
     "legendFormat": "source_id = {{source_id}}"
    }
   ]
  },
  {
   "title": "ExchangeService throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "B/s" }
   ],
   "targets": [
    {
     "expr": "rate(stream_exchange_data_size[15s])",
     "legendFormat": "{{up_actor_id}}->{{down_actor_id}}"
    }
   ]
  },
  { "title": "Hummock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "read ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_duration_count[1m])) by (job,instance)",
     "legendFormat": "get - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_scan_duration_count[1m])) by (job,instance)",
     "legendFormat": "range_scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_duration_count[1m])) by (job,instance)",
     "legendFormat": "reverse_range_scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_get_shared_buffer_hit_counts[1m])) by (job,instance)",
     "legendFormat": "shared_buffer hit - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "read duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance)(rate(state_store_get_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_get_duration_count[1m]))",
     "legendFormat": "get avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_scan_duration_sum[1m])) / sum by(le, job,instance) (rate(state_store_range_scan_duration_count[1m]))",
     "legendFormat": "range_scan avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_reverse_scan_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_range_reverse_scan_duration_count[1m]))",
     "legendFormat": "reverse_range_scan avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "block ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_sst_store_block_request_counts[1m])) by (instance, type)",
     "legendFormat": "{{type}} - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(state_store_meta_cache_size) by (job,instance)",
     "legendFormat": "meta-cache - {{job}} @ {{instance}}"
    },
    {
     "expr": "avg(state_store_block_cache_size) by (job,instance)",
     "legendFormat": "meta-cache - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "write ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_duration_count[1m])) by (job,instance)",
     "legendFormat": "write batch - {{job}} @ {{instance}} "
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_l0_duration_count[1m])) by (job,instance)",
     "legendFormat": "l0 - {{job}} @ {{instance}} "
    }
   ]
  },
  {
   "title": "write duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_batch_duration_sum[1m]))  / sum by(le, job, instance)(rate(state_store_write_batch_duration_count[1m]))",
     "legendFormat": "shared_buffer avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_sum[1m]))  / sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_count[1m]))",
     "legendFormat": "sync_remote avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "sst read counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_bloom_filter_true_negative_counts[1m])) by (job,instance)",
     "legendFormat": "bloom filter true negative  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_bloom_filter_might_positive_counts[1m])) by (job,instance)",
     "legendFormat": "bloom filter might positive  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_sum[1m]))  / sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_count[1m]))",
     "legendFormat": "# merged ssts avg  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "read throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(job,instance)(rate(state_store_get_key_size_sum[1m])+rate(state_store_get_value_size_sum[1m]))/sum by(job,instance)(rate(state_store_get_key_size_count[1m]))",
     "legendFormat": "get  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(job,instance)(rate(state_store_get_key_size_sum[1m]))/sum by(job,instance)(rate(state_store_get_key_size_count[1m]))",
     "legendFormat": "get key  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(job,instance)(rate(state_store_get_value_size_sum[1m]))/sum by(job,instance)(rate(state_store_get_value_size_count[1m]))",
     "legendFormat": "get value  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(job,instance)(rate(state_store_range_scan_size_sum[1m]))/sum by(job,instance)(rate(state_store_range_scan_size_count[1m]))",
     "legendFormat": "range_scan  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(job,instance)(rate(state_store_range_reverse_scan_size_sum[1m]))/sum by(job,instance)(rate(state_store_range_reverse_scan_size_count[1m]))",
     "legendFormat": "reverse_range_scan  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "write kv pair counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_tuple_counts[1m])) by (job,instance)",
     "legendFormat": "write_batch_kv_pair_count - {{instance}} "
    }
   ]
  },
  {
   "title": "write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_size_sum[1m]))by(job,instance) / sum(rate(state_store_write_batch_size_count[1m]))by(job,instance)",
     "legendFormat": "shared_buffer - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_sstable_size_sum[1m]))by(job,instance) / sum(rate(state_store_shared_buffer_to_sstable_size_count[1m]))by(job,instance)",
     "legendFormat": "sync - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "build sstable duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "merge iterators ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_merge_seek_duration_count[1m])) by (job,instance)",
     "legendFormat": "MI seek  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_iter_merge_next_duration_count[1m])) by (job,instance)",
     "legendFormat": "MI next  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "row seq scan next duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_sum[1m])) / sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_count[1m]))",
     "legendFormat": "row_seq_scan next avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "merge iterators duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_iter_merge_seek_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_iter_merge_seek_duration_count[1m]))",
     "legendFormat": "mi_seek avg  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "gRPC Hummock Table Comparision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true,
   "panels": [
    {
     "title": "get new TableID latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance)) ",
       "legendFormat": "hummock_client_ GetNewTableId_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ GetNewTableId_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_GetNewTableId_p99 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p99 - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hummock Compation Comparision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "report compation latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "report compation latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "report compation latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p99 - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hummock Version Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "pin version latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p90 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p99 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p90 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p99 - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Catalog Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "create latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Create\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Create\"}[1m]))",
       "legendFormat": "Create_avg"
      }
     ]
    },
    {
     "title": "drop latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Drop\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Drop\"}[1m]))",
       "legendFormat": "Drop_avg"
      }
     ]
    },
    {
     "title": "get catalog latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/GetCatalog\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/GetCatalog\"}[1m]))",
       "legendFormat": "GetCatalog_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "add worker node latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/AddWorkerNode\"}[1m]))",
       "legendFormat": "AddWorkerNode_avg"
      }
     ]
    },
    {
     "title": "list all node latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/ListAllNodes\"}[1m]))",
       "legendFormat": "ListAllNodes_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Stream Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "collapsed": true,
   "panels": [
    {
     "title": "create materialized view latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m]))",
       "legendFormat": "CreateMaterializedView_avg"
      }
     ]
    },
    {
     "title": "drop materialized view latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m]))",
       "legendFormat": "DropMaterializedView_avg"
      }
     ]
    },
    {
     "title": "flush latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/Flush\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/Flush\"}[1m]))",
       "legendFormat": "Flush_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC meta: Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "version latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m]))",
       "legendFormat": "UnpinVersion_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinVersion\"}[1m]))",
       "legendFormat": "PinVersion_avg"
      }
     ]
    },
    {
     "title": "snapshot latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m]))",
       "legendFormat": "UnpinSnapshot_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m]))",
       "legendFormat": "PinSnapshot_avg"
      }
     ]
    },
    {
     "title": "compation latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m]))",
       "legendFormat": "ReportCompactionTasks_avg"
      }
     ]
    },
    {
     "title": "table latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/AddTables\"}[1m]))",
       "legendFormat": "AddTables_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m]))",
       "legendFormat": "GetNewTableId_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC: hummock meta client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_report_compaction_task_counts[1m])) by(job,instance)",
       "legendFormat": "report_compaction_task_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "version_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_version_latency_sum[1m])) / sum(irate(state_store_pin_version_latency_count[1m]))",
       "legendFormat": "pin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_latency_sum[1m])) / sum(irate(state_store_unpin_version_latency_count[1m]))",
       "legendFormat": "unpin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "version_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_version_counts[1m])) by(job,instance)",
       "legendFormat": "pin_version_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_counts[1m])) by(job,instance)",
       "legendFormat": "unpin_version_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_snapshot_latency_sum[1m])) / sum(irate(state_store_pin_snapshot_latency_count[1m]))",
       "legendFormat": "pin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_snapshot_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_snapshot_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_latency_sum[1m])) / sum(irate(state_store_unpin_snapshot_latency_count[1m]))",
       "legendFormat": "unpin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_snapshot_counts[1m])) by(job,instance)",
       "legendFormat": "pin_snapshot_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_counts[1m])) by(job,instance)",
       "legendFormat": "unpin_snapshot_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "table_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le,instance))",
       "legendFormat": "pin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "add_table_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "add_table_latency_p90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_add_tables_latency_sum[1m])) / sum(irate(state_store_add_tables_latency_count[1m]))",
       "legendFormat": "add_table_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_latency_sum[1m])) / sum(irate(state_store_get_new_table_id_latency_count[1m]))",
       "legendFormat": "get_new_table_id_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "table_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(irate(state_store_add_tables_counts[1m]))by(job,instance)",
       "legendFormat": "add_tables_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_counts[1m]))by(job,instance)",
       "legendFormat": "get_new_table_id_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "compation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p50 - {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p99 - {{instance}}"
      },
      {
       "expr": "sum(irate(state_store_report_compaction_task_latency_sum[1m])) / sum(irate(state_store_report_compaction_task_latency_count[1m]))",
       "legendFormat": "report_compaction_task_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p90 - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}